// Writes src/model/sprites.ts: the object sprite frames ($22-$2E) from
// thrusty-levels/src/sprites.asm. Run: node scripts/gen-sprites.ts
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const here = (p: string) => fileURLToPath(new URL(p, import.meta.url));
const asm = readFileSync(here('../../thrusty-levels/src/sprites.asm'), 'utf8');
const FIRST = 0x22;
const LAST = 0x2e;

const frames = new Map<number, number[]>();
let cur = -1;
for (const line of asm.split('\n')) {
  const head = /^\/\/ sprite \$([0-9a-f]+)/i.exec(line);
  if (head) {
    cur = parseInt(head[1], 16);
    frames.set(cur, []);
    continue;
  }
  const row = /\.byte\s+%([01]{8}),%([01]{8}),%([01]{8})/.exec(line);
  if (row && frames.has(cur)) frames.get(cur)!.push(parseInt(row[1] + row[2] + row[3], 2));
}

const hex = (n: number) => '0x' + n.toString(16).padStart(6, '0');
let out = `// GENERATED by scripts/gen-sprites.ts from thrusty-levels/src/sprites.asm.
// Object sprite frames: 21 lines of 24 hi-res pixels, bit 23 = leftmost.

export const SPRITE_W = 24;
export const SPRITE_H = 21;
export const SPRITE_FIRST = 0x${FIRST.toString(16)};

/** Frames $${FIRST.toString(16)}-$${LAST.toString(16)}, indexed by frame - SPRITE_FIRST. */
export const SPRITES: number[][] = [
`;
for (let f = FIRST; f <= LAST; f++) {
  const lines = frames.get(f);
  if (!lines || lines.length !== 21) throw new Error(`sprite $${f.toString(16)}: ${lines?.length ?? 0} lines`);
  out += `  // $${f.toString(16)}\n  [${lines.map(hex).join(', ')}],\n`;
}
out += '];\n';
writeFileSync(here('../src/model/sprites.ts'), out);
console.log('wrote src/model/sprites.ts');
