"""Annotations: main block part 1 ($8283-$8F0A)
landscape drawing, objects, raster IRQ chain, sprite multiplexer, keyboard."""

LABELS = {
    0x8283: 'unused_bit_table',
    # objects
    0x84e9: 'obj_colour_gun',
    0x84ea: 'obj_colour_fuel',
    0x84eb: 'obj_colour_fuel_2',
    0x84ec: 'obj_colour_pod_stand',
    0x84ed: 'obj_colour_generator',
    0x84ee: 'obj_colour_generator_2',
    0x84ef: 'obj_colour_door_switch',
    0x84f0: 'objects_processed',
    0x8571: 'update_and_draw_all_objects',
    0x857e: 'update_objects_loop',
    0x85b8: 'not_pod_stand',
    0x85db: 'not_generator',
    0x85f3: 'object_is_active',
    0x8608: 'destroy_generator',
    0x869c: 'bullet_test_next_jmp',
    0x869f: 'explosion_at_bullet',
    0x86b8: 'bullet_hit_not_generator',
    0x86e5: 'bullet_test_next',
    0x86eb: 'object_fuel_and_guns',
    0x86ef: 'object_guns_jmp',
    0x86f2: 'test_fuel_collect',
    0x8740: 'object_gun_fire',
    0x87a2: 'object_generator_smoke',
    0x87ef: 'object_draw',
    0x8850: 'object_offscreen',
    0x8851: 'object_onscreen',
    0x8868: 'object_sprite_coords',
    0x8883: 'object_not_first',
    0x889b: 'plot_object_sprite',
    0x88c3: 'plot_object_gun',
    0x88d2: 'plot_object_fuel',
    0x88f2: 'plot_object_fuel_single',
    0x8901: 'plot_object_pod_stand',
    0x891a: 'plot_object_generator',
    # raster interrupt chain
    0x8933: 'sprite_list_offset',
    0x8934: 'sprite_list_count',
    0x8936: 'sprite_bands_ready',
    0x8937: 'sprite_bands_busy',
    0x8938: 'sprite_band_rotate',
    0x8939: 'hires_status_flag',
    0x893a: 'multicolour_flag',
    0x893b: 'playfield_bg_colour',
    0x893c: 'playfield_mc2_colour',
    0x893d: 'irq_exit',
    0x8943: 'irq_handler',
    0x8958: 'irq_other',
    0x8964: 'irq_raster',
    0x8993: 'irq_raster_wrap',
    0x89b8: 'irq_jump_vector',
    0x89ba: 'irq_jump_table_LO',
    0x89bf: 'irq_jump_table_HI',
    0x89c4: 'irq_top_of_frame',
    0x8a8c: 'irq_multicolour_on',
    0x89d1: 'irq_frame_no_commit',
    0x89ec: 'irq_band_rotate_ok',
    0x8a0e: 'irq_no_planet_flash',
    0x8a17: 'irq_set_status_screen',
    0x8a3e: 'irq_status_bar_line',
    0x8a4d: 'irq_playfield_start',
    0x8a53: 'irq_wait_playfield',
    0x8a73: 'irq_set_ctrl2',
    0x8a74: 'irq_wait_playfield_2',
    0x8a8c: 'irq_multicolour_on',
    0x8a9c: 'irq_sprite_band_end',
    0x8aa1: 'irq_sprite_band',
    0x8aaf: 'irq_sprite_band_loop',
    0x8ac3: 'irq_skip_sprites',
    0x8acf: 'irq_sprite_set',
    0x8ad8: 'irq_sprite_index_ok',
    0x8afd: 'irq_sprite_x_msb_clear',
    0x8b08: 'irq_sprite_xy',
    0x8b29: 'bit_table',
    0x8b31: 'planet_flash_colours',
    # sprite multiplexer
    0x8b41: 'sprite_list_clear',
    0x8b52: 'sprite_list_add',
    0x8b5a: 'sprite_list_add_ok',
    0x8b5f: 'sprite_list_copy',
    0x8b72: 'sprite_list_find_pos',
    0x8b85: 'sprite_list_insert',
    0x8b8f: 'sprite_list_shift',
    0x8b96: 'sprite_list_insert_pos',
    0x8ba7: 'sprite_bands_finish',
    0x8bb2: 'sprite_bands_finish_2',
    0x8be5: 'sprite_bands_finish_jmp',
    0x8be8: 'sprite_bands_build',
    0x8c01: 'sprite_bands_next',
    0x8c16: 'sprite_bands_copy',
    0x8c47: 'sprite_bands_new_band',
    0x8c54: 'sprite_bands_close_band',
    0x8c68: 'sprite_bands_count_ok',
    0x8c7f: 'sprite_bands_raster',
    0x8c9a: 'sprite_bands_commit_rts',
    0x8c9b: 'sprite_bands_commit',
    0x8ca3: 'sprite_bands_copy_list',
    0x8cb7: 'sprite_bands_commit_mc',
    0x8cbc: 'sprite_bands_copy_irq',
    0x8cc8: 'check_collisions',
    0x8cd6: 'check_collisions_2',
    0x8cdf: 'check_ship_hits_sprite',
    0x8ce8: 'check_sprite_bg',
    0x8cf7: 'check_pod_bg',
    0x8d06: 'pod_collided',
    0x8d0a: 'set_ship_and_pod_sprites',
    0x8d4e: 'sprite_bands_commit_hires',
    0x8d53: 'sprite_bands_copy_irq_2',
    # keyboard
    0x8d6f: 'key_matrix_to_ascii',
    0x8daf: 'key_last_1',
    0x8db0: 'key_last_2',
    0x8db1: 'key_ascii',
    0x8db2: 'key_matrix_checksum',
    0x8db3: 'read_key_ascii',
    0x8db7: 'read_key_wait',
    0x8dd1: 'read_key_check_2',
    0x8de0: 'read_key_released',
    0x8ded: 'read_key_shift',
    0x8df8: 'read_key_scan',
    0x8dfc: 'read_key_scan_row',
    0x8e01: 'read_key_scan_bit',
    0x8e06: 'read_key_next_bit',
    0x8e14: 'read_key_found',
    0x8e35: 'key_matrix_checksum_calc',
    0x8e3a: 'key_matrix_checksum_loop',
    0x8e42: 'read_key_reset',
    # font
    0x8e51: 'font_byte_mask',
    0x8e52: 'font_data_line_0',
    0x8e77: 'font_data_line_1',
    0x8e9c: 'font_data_line_2',
    0x8ec1: 'font_data_line_3',
    0x8ee6: 'font_data_line_4',
}

RAM_LABELS = {
    0x0b00: 'column_bitmap_offset_LO',
    0x0b50: 'column_bitmap_offset_HI',
    0x0ba0: 'column_pixel_byte',
    0x0c00: 'sprite_display_list',
    0x0d00: 'sprite_build_list',
    0x0e80: 'raster_build_table',
    0x0f00: 'sprite_entries',
    0x07c0: 'sprite_sort_order',
    0x5ff8: 'sprite_pointers_screen_A',
    0x57f8: 'sprite_pointers_screen_B',
}

ZP = {
    0xa8: 'spr_frame', 0xa9: 'spr_colour', 0xaa: 'spr_x_lo', 0xab: 'spr_x_hi', 0xac: 'spr_y',
    0xad: 'irq_table_index', 0xae: 'irq_sprite_index', 0xaf: 'sprite_list_len', 0xb0: 'raster_table_len',
    0xb1: 'irq_band_skip', 0xb2: 'irq_hw_sprite', 0xb3: 'irq_band_rotate', 0xb4: 'sprite_band_count_pos',
    0xb5: 'text_ptr', 0xb6: 'text_ptr_HI',
    0xfd: 'key_bits',
}

ZP_COMMENTS = {
    0xa8: 'sprite to add: frame (sprite pointer)',
    0xa9: 'sprite to add: colour',
    0xaa: 'sprite to add: X (low 8 bits)',
    0xab: 'sprite to add: X bit 8 / $FF = do not draw',
    0xac: 'sprite to add: Y',
    0xad: 'offset of current entry in raster_table ($0E00)',
}

COMMENTS = {
    0x8571: 'reset sprite frame/colour',
    0x8575: 'count objects processed this frame',
    0x85dd: 'assume not drawn',
    0x87f1: 'object on screen?',
    0x881d: 'assume not visible',
    0x8835: 'remove status bar rows',
    0x8868: 'convert to sprite coordinates:',
    0x886c: 'Y * 2 + 50 (top border)',
    0x8874: 'X * 4 (9 bits)',
    0x88b4: 'door switch: frames $2C/$2D',
    0x88c3: 'gun: frames $22-$25 by direction',
    0x88d2: 'fuel: alternate drawing every other object',
    0x8901: 'pod stand: two sprites',
    0x891a: 'generator: two sprites',
    0x8946: 'raster interrupt?',
    0x894b: 'CIA timer interrupt?',
    0x8952: 'CIA timer: game timing tick',
    0x8969: 'current raster table entry',
    0x896b: 'next entry raster line ($FF = last)',
    0x8973: 'schedule next interrupt',
    0x8979: 'handler number for this entry',
    0x8993: 'last entry: restart table at top of frame',
    0x89a7: 'first raster line',
    0x89c4: 'black background in the border area',
    0x89c9: 'new sprite bands ready?',
    0x89d7: 'disable multiplexed sprites (keep 6 and 7)',
    0x89df: 'rotate starting sprite each frame (0-5)',
    0x89f2: 'scan keyboard',
    0x89f5: 'planet explosion: flash the background',
    0x8a0e: 'status bar: text mode, double buffered screen',
    0x8a1a: 'text mode, display on',
    0x8a22: 'status bar colours',
    0x8a32: 'sound effects',
    0x8a35: 'read joystick / keys',
    0x8a38: 'music',
    0x8a3e: 'wait for end of status bar line',
    0x8a4d: 'switch to bitmap mode',
    0x8a53: 'wait for start of playfield',
    0x8a5a: 'bitmap at $6000',
    0x8a6a: 'multicolour unless hires flag',
    0x8a8c: 'multicolour on (bottom of screen)',
    0x8aa1: 'sprite band: position up to 6 hardware sprites',
    0x8adb: 'sprite pointer in both screens',
    0x8ae3: 'colour',
    0x8aed: 'X bit 8',
    0x8b0c: 'X',
    0x8b12: 'Y',
    0x8b19: 'enable sprite',
    0x8b55: 'list full (31 sprites)?',
    0x8b5f: 'copy frame, colour, x lo, x hi, y',
    0x8b72: 'insertion sort on Y',
    0x8c9b: 'busy building?',
    0x8ca3: 'copy build list to display list',
    0x8cd0: 'clear collision latches',
    0x8cdf: 'sprite-sprite collision',
    0x8ceb: 'sprite-background collision',
    0x8cee: 'bit 7: ship (sprite 7) hit background',
    0x8cf7: 'bit 6: pod (sprite 6) hit background',
    0x8d0a: 'ship = sprite 7',
    0x8d1f: 'pod = sprite 6',
    0x8db3: 'wait for a new key and return its ASCII code',
    0x8dfc: 'scan the 8 keyboard matrix rows read in the IRQ',
    0x8e27: 'convert to ASCII',
    0x8e35: 'XOR of all matrix rows (changes when a key changes)',
}

BLOCK_COMMENTS = {
    0x8283: 'Unused bit table',
    0x84e9: """Object sprite colours (C64 objects are hardware sprites)""",
    0x8571: """update_and_draw_all_objects
Walks the level object table: guns fire, fuel can be collected, bullets that
hit objects destroy them, the generator smokes, and every visible object is
added to the sprite multiplexer list.""",
    0x889b: """plot_object_sprite
Adds the current object to the sprite list (frame in spr_frame, colour in
spr_colour, coordinates already set by object_visibility_test).""",
    0x8933: 'Raster interrupt / sprite multiplexer variables',
    0x8943: """IRQ handler (via KERNAL $0314)
Raster interrupts walk raster_table ($0E00): each 3-byte entry is
[raster line, handler number, next raster line or $FF]. Handlers:
  0 irq_top_of_frame     status bar setup, keyboard, sound, music
  1 irq_sprite_band      position the next band of multiplexed sprites
  2 irq_status_bar_line  colour change under the status bar
  3 irq_playfield_start  switch to bitmap mode for the playfield
  4 irq_multicolour_on
The CIA 1 timer interrupt decrements game_tick_timer (main loop timing).""",
    0x89c4: 'Raster handler 0: top of frame',
    0x8aa1: """Raster handler 1: sprite band
Takes the next group of entries from sprite_display_list ($0C00) - 5 bytes
each: frame, colour, x lo, x hi, y - and assigns them to hardware sprites 0-5
in rotation. The rotating start index spreads flicker when a band has more
than 6 sprites.""",
    0x8b29: 'Bit masks 1 << n',
    0x8b31: 'Background colours for the planet explosion flash',
    0x8b41: """Sprite multiplexer
Objects, bullets etc. add sprites with sprite_list_add each frame.
sprite_bands_build sorts them into raster bands 12 lines apart and builds the
raster interrupt table; sprite_bands_commit (called from the IRQ) copies the
finished lists for display. Sprites 6 (pod) and 7 (ship) are not multiplexed.""",
    0x8b52: 'Add sprite (spr_frame..spr_y) to the list, keeping it sorted by Y',
    0x8be8: 'Split the sorted sprite list into raster bands',
    0x8c9b: """Commit the new sprite bands for display (from the IRQ), then read the
hardware collision registers and position the ship and pod sprites.""",
    0x8d6f: 'Keyboard matrix index -> ASCII (row * 8 + column)',
    0x8db3: 'Keyboard input for the high score name entry',
    0x8e51: """Status bar font: 37 characters (space, A-Z, digits ...), 5 rows of
one byte each, stored row by row""",
}

FORMATS = {
    0x89ba: ('lo', 0x89bf), 0x89bf: ('hi', 0x89ba),
    0x84f1: ('rows', 9), 0x84fa: ('rows', 9),
    0x8d6f: ('text', ),
    0x8e52: ('rows', 16), 0x8e77: ('rows', 16), 0x8e9c: ('rows', 16), 0x8ec1: ('rows', 16), 0x8ee6: ('rows', 16),
}

TABLES = {}

RAM_TABLES = {
    0x4000: (0x4d00, 'sprite_gfx'),
    0x5400: (0x57f8, 'screen_B'),
    0x5800: (0x5c00, 'status_charset'),
    0x5c00: (0x5ff8, 'screen_A'),
    0x5ff8: (0x6000, 'sprite_pointers_screen_A'),
    0x57f8: (0x5800, 'sprite_pointers_screen_B'),
    0x6000: (0x8000, 'bitmap'),
    0xd800: (0xdc00, 'COLOR_RAM'),
    0x0c00: (0x0d00, 'sprite_display_list'),
    0x0d00: (0x0e00, 'sprite_build_list'),
    0x0e80: (0x0f00, 'raster_build_table'),
    0x0f00: (0x1000, 'sprite_entries'),
}

OPERAND = {
    0x896b: 'raster_table+2,y',
    0x8973: 'raster_table+3,y',
    0x8979: 'raster_table+1,y',
    0x8993: 'raster_table+1,y',
    0x8b93: 'sprite_sort_order+1,x',
    0x8ca3: 'sprite_build_list-1,x',
    0x8ca6: 'sprite_display_list-1,x',
    0x8cbc: 'raster_build_table-1,x',
    0x8cbf: 'raster_table+5,x',
    0x8d53: 'raster_build_table-1,x',
    0x8d56: 'raster_table+8,x',
    0x8d5e: 'raster_table+6',
    0x8d63: 'raster_table+7',
    0x8d68: 'raster_table+8',
}
RAM_TABLES[0x0e06] = (0x0e80, 'raster_table_bands')
RAM_TABLES[0x5300] = (0x5400, 'line_sprite_data')

RAM_COMMENTS = {
    0x0180: 'score, 3 bytes BCD',
    0x0400: 'left wall X per world row (256 entries, circular)',
    0x0500: 'right wall X per world row',
    0x0600: 'particle tables: 32 entries each',
    0x07c0: 'sprite multiplexer: sorted entry offsets',
    0x07e0: 'per-object tractor beam counters',
    0x08c0: 'saved KERNAL IRQ vector',
    0x09f7: 'terrain drawing state (previous frame X per row)',
    0x0b00: 'terrain column -> bitmap byte offset (80 columns)',
    0x0ba0: 'terrain column -> pixel pattern ($A0 left / $0A right half)',
    0x0c00: 'sprite bands being displayed (5 bytes per sprite)',
    0x0d00: 'sprite bands being built',
    0x0e80: 'raster table being built',
    0x0f00: 'sprite list: frame, colour, x lo, x hi, y',
    0x5300: 'tether line sprites (frames $4C-$4F)',
    0x5400: 'screen matrix B: playfield colours with invisible terrain',
    0x5c00: 'screen matrix A: status bar + playfield colours',
    0x6000: 'multicolour bitmap',
}
