#!/usr/bin/env python3
"""Write src/title_qr_data.asm: a QR code for the title screen.

    python3 packages/thrusty-levels/tools/qr2asm.py [URL]

The code is drawn by plot_qr_code (src/title_qr.asm) on 8x8 hires bitmap
cells, one QR module = 2 pixels x 2 lines (square on screen), so the grid is
32x32 modules: the QR code plus a light quiet zone around it.

Data: per cell row, 16 bytes; byte j covers cell j/2, lines 4*(j%2)..+3:
high nibble = the 4 modules of the first line pair, low nibble = the second
(bit 3 = leftmost module, 1 = light). An upper-case URL fits a smaller code
(alphanumeric mode); GitHub URLs do not mind the case.
"""
import sys
from pathlib import Path

import qrcode

URL = sys.argv[1] if len(sys.argv) > 1 else "HTTPS://GITHUB.COM/HAYESMAKER/THRUST-C64"
GRID = 32  # 8 cells x 4 modules
OUT = Path(__file__).resolve().parent.parent / "src" / "title_qr_data.asm"

qr = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_L, border=0)
qr.add_data(URL)
qr.make(fit=True)
m = qr.get_matrix()  # True = dark
n = len(m)
if n + 6 > GRID:
    sys.exit(f"QR code is {n}x{n} modules: too big for {GRID}x{GRID} with a quiet zone (shorter URL?)")
off = (GRID - n + 1) // 2  # quiet zone: left/top get the odd module

def light(x, y):
    x -= off
    y -= off
    return not (0 <= x < n and 0 <= y < n and m[y][x])

data = []
for cell_row in range(GRID // 4):
    for j in range(16):
        cell, half = j // 2, j % 2
        byte = 0
        for pair in range(2):  # high nibble, low nibble
            y = cell_row * 4 + half * 2 + pair
            nib = 0
            for k in range(4):
                if light(cell * 4 + k, y):
                    nib |= 8 >> k
            byte |= nib << (4 if pair == 0 else 0)
        data.append(byte)

lines = [
    "// GENERATED by packages/thrusty-levels/tools/qr2asm.py - do not edit.",
    f'// QR code (version {qr.version}, {n}x{n} modules, error correction L) for:',
    f"//   {URL}",
    "// Drawn by plot_qr_code (title_qr.asm). '#' = dark module:",
]
for y in range(GRID):
    lines.append("//   " + "".join("." if light(x, y) else "#" for x in range(GRID)))
lines.append("qr_data:")
for i in range(0, len(data), 16):
    lines.append("    .byte " + ",".join(f"${b:02x}" for b in data[i : i + 16]) + f"  // cell row {i // 16}")
OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT} ({len(data)} bytes, QR version {qr.version}, {n}x{n})")
